# Generated by Django 6.0.6 on 2026-06-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_elite_plan_and_pdf_limits'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_url',
            field=models.URLField(blank=True, help_text='Profile Image URL', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='base_resume',
            field=models.TextField(blank=True, help_text="User's core career history"),
        ),
        migrations.AddField(
            model_name='profile',
            name='default_font',
            field=models.CharField(default='Inter', help_text='Preferred Studio Font', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='default_language',
            field=models.CharField(default='English', help_text='Preferred Output Language', max_length=50),
        ),
    ]
