# Generated by Django 6.0.6 on 2026-06-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_avatar_url_profile_base_resume_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar_url',
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Profile Image', null=True, upload_to='avatars/'),
        ),
    ]
