# Generated by Django 6.0.7 on 2026-09-22 18:16

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_stripe_subscription_and_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Profile Image', null=True, upload_to=users.models.avatar_upload_to),
        ),
    ]
