# Generated by Django 6.0.7 on 2026-09-22 18:29

from django.db import migrations, models


def grandfather_existing_accounts(apps, schema_editor):
    """
    Accounts created before confirmation existed are treated as confirmed.

    They signed up under rules that never asked for it, and switching the
    requirement on must not suddenly take away generations they already had.
    """
    Profile = apps.get_model('users', 'Profile')
    Profile.objects.update(email_verified=True)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_avatar_random_filenames'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(grandfather_existing_accounts, migrations.RunPython.noop),
    ]
