"""
Django settings for aigen project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from pathlib import Path
import dj_database_url
from dotenv import load_dotenv

try:
    import sentry_sdk
except ImportError:
    sentry_sdk = None

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env file
load_dotenv(dotenv_path=BASE_DIR / '.env')

from django.core.exceptions import ImproperlyConfigured

# SECURITY: Load secret key from environment variable
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-local-dev-only-change-me')

# SECURITY: DEBUG off in production
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

if not DEBUG and ('test' not in sys.argv) and (not SECRET_KEY or SECRET_KEY == 'django-insecure-local-dev-only-change-me'):
    raise ImproperlyConfigured("SECRET_KEY must be set in production when DEBUG=False.")

# SECURITY: Restrict allowed hosts
# Render sets RENDER_EXTERNAL_HOSTNAME automatically (e.g. mysite.onrender.com)
_allowed = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
_render_host = os.environ.get('RENDER_EXTERNAL_HOSTNAME', '')
if _render_host:
    _allowed.append(_render_host)
ALLOWED_HOSTS = [h.strip() for h in _allowed if h.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'generator',
    'users',
    'storages',
]

MIDDLEWARE = [
    # First on purpose: Render's health probe is plain HTTP with an internal
    # Host header, which the next two would redirect or reject.
    'aigen.middleware.HealthCheckMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'aigen.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'aigen.wsgi.application'


# Database
# Uses PostgreSQL in production (DATABASE_URL), SQLite locally
DATABASES = {
    'default': dj_database_url.config(
        default='sqlite:///' + str(BASE_DIR / 'db.sqlite3'),
        conn_max_age=600
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# STORAGES (WhiteNoise for static, S3 or disk for media) is set at the bottom
# of this file, next to the S3 settings it depends on.

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Auth redirects
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'login'
LOGIN_URL = 'login'

# ── Stripe Configuration ────────────────────────────────────────────────────
STRIPE_SECRET_KEY      = os.environ.get('STRIPE_SECRET_KEY', '')
STRIPE_PUBLISHABLE_KEY = os.environ.get('STRIPE_PUBLISHABLE_KEY', '')
STRIPE_WEBHOOK_SECRET  = os.environ.get('STRIPE_WEBHOOK_SECRET', '')

# Per-plan Price IDs  (create recurring prices in your Stripe Dashboard)
# Set these in your .env / Render/Railway env vars:
#   STRIPE_PRICE_ID_PRO   = price_xxxxxxxxxxxxxxxx   ($5/mo)
#   STRIPE_PRICE_ID_ELITE = price_yyyyyyyyyyyyyyyy   ($10/mo)
STRIPE_PRICE_ID_PRO   = os.environ.get('STRIPE_PRICE_ID_PRO',   '')
STRIPE_PRICE_ID_ELITE = os.environ.get('STRIPE_PRICE_ID_ELITE', '')


# ── AI provider ──────────────────────────────────────────────────────────────
# Django calls Anthropic directly. Without this key no endpoint can generate
# anything, so it is worth failing loudly at startup rather than letting every
# request return a vague error.
#
# There used to be a FastAPI worker between Django and the provider, reached
# over AI_SERVICE_URL with a shared AI_SERVICE_TOKEN. It has been deleted; both
# of those settings are gone. The hop could not work on hosting without private
# networking between services — the internal address did not resolve, and the
# public URL sent each call out through the platform edge, which rate-limited
# it with a 429 the worker never saw.
ANTHROPIC_API_KEY = os.environ.get('ANTHROPIC_API_KEY', '')
ANTHROPIC_MODEL = os.environ.get('ANTHROPIC_MODEL', 'claude-sonnet-5')

# Hard stop on total tokens per UTC day across all users (0 = no limit). Every
# call's usage is counted in the cache either way; see generator/ai_client.py.
AI_DAILY_TOKEN_BUDGET = int(os.environ.get('AI_DAILY_TOKEN_BUDGET', '0') or 0)

# USD per million tokens, (input, output), for the staff cost page. Anthropic
# first-party list prices as of 2026-06; thinking tokens bill as output. Only an
# estimate — the Anthropic console invoice is the real figure.
AI_PRICES_PER_MTOK = {
    'claude-sonnet-5':  (2.00, 10.00),
    'claude-opus-5':    (5.00, 25.00),
    'claude-haiku-4-5': (1.00, 5.00),
}

if not ANTHROPIC_API_KEY:
    import warnings
    warnings.warn(
        "ANTHROPIC_API_KEY is not set. Every AI endpoint — resume generation, "
        "cover letters, the rewriter, ATS scoring, interview prep and "
        "follow-up drafts — will return a configuration error until it is.",
        RuntimeWarning,
    )


# ── Email ────────────────────────────────────────────────────────────────────
# Any SMTP provider (Resend, Postmark, SendGrid, Mailgun, SES...) via these env
# vars. Without EMAIL_HOST nothing is sent: messages go to the log, the
# password-reset page says reset is unavailable, and email confirmation is not
# required — so an unconfigured deploy never locks new users out.
EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
EMAIL_CONFIGURED = bool(EMAIL_HOST)
if EMAIL_CONFIGURED:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
    EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
    EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
    EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
    EMAIL_USE_SSL = os.environ.get('EMAIL_USE_SSL', 'False') == 'True'
    EMAIL_TIMEOUT = 10
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'CVAI <no-reply@cvai.work>')

# Free generations only after the account's email is confirmed. Every free
# account is three paid model calls, so unconfirmed sign-ups were free credit
# for anyone with a list of throwaway addresses. Defaults to on exactly when
# email can actually be delivered.
REQUIRE_EMAIL_VERIFICATION = os.environ.get(
    'REQUIRE_EMAIL_VERIFICATION', 'True' if EMAIL_CONFIGURED else 'False'
) == 'True'


# ── Cache (Redis in production, LocMem fallback for local dev) ──────────────
# REDIS_URL is injected automatically by Render via fromService → connectionString.
# Locally, leave it unset — LocMemCache is fine for a single-process dev server.
_REDIS_URL = os.environ.get('REDIS_URL', '')

if _REDIS_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': _REDIS_URL,
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                # Drop stale connections instead of raising on network hiccup
                'IGNORE_EXCEPTIONS': True,
            },
            # Namespace keeps keys isolated if you ever share this Redis instance
            'KEY_PREFIX': 'mysite',
        }
    }
    # Sessions are read from Redis and written through to the database.
    # Cache-only sessions were lost whenever Redis restarted or evicted keys —
    # the free Redis plan persists nothing — which logged everyone out; and
    # with IGNORE_EXCEPTIONS a Redis outage silently dropped every new session.
    SESSION_ENGINE = 'django.contrib.sessions.backends.cached_db'
    SESSION_CACHE_ALIAS = 'default'
else:
    # Safe default for local development — no Redis required
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        }
    }


# ── CSRF Trusted Origins ────────────────────────────────────────────────────
# Required for POST requests from the production domain (Stripe webhooks, forms).
# Render sets RENDER_EXTERNAL_HOSTNAME; APP_URL covers custom domains.
_csrf_origins = []
if _render_host:
    _csrf_origins.append(f'https://{_render_host}')
_app_url = os.environ.get('APP_URL', '')  # e.g. https://cvai.io
if _app_url:
    _csrf_origins.append(_app_url.rstrip('/'))
if _csrf_origins:
    CSRF_TRUSTED_ORIGINS = _csrf_origins


# ── Production Security (only when DEBUG=False) ─────────────────────────────
#
# Skipped under the test runner. SECURE_SSL_REDIRECT turns every request the
# Django test client makes into a 301 to https before it reaches a view, so a
# suite run with DEBUG=False fails wholesale on status codes — "301 != 401" on
# the auth guards, and so on down the file. Developers hit DEBUG=True from a
# local .env and never see it; CI has no .env, so every run failed for a reason
# that had nothing to do with the code under test.
#
# The redirect itself is what production needs, and production does not run the
# test runner — so gating it here costs nothing and keeps CI meaningful.
TESTING = 'test' in sys.argv

if not DEBUG and not TESTING:
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31_536_000       # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True


# ── Structured Logging ──────────────────────────────────────────────────────
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{asctime} [{levelname}] {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django.request': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'stripe': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}


# ── Sentry Error Tracking ───────────────────────────────────────────────────
# Set SENTRY_DSN in your environment (Render dashboard / .env).
# Left empty = Sentry silently disabled — safe for local dev.
SENTRY_DSN = os.environ.get('SENTRY_DSN', '')
# Never from the test runner: a DSN in a developer's .env otherwise reports
# the suite's deliberate failures to the production project.
if SENTRY_DSN and sentry_sdk and not TESTING:
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        traces_sample_rate=0.1,           # 10% of requests traced (tune for cost)
        send_default_pii=False,           # GDPR: don't send user IPs/emails to Sentry
        environment='production' if not DEBUG else 'development',
    )
# ── Медиа файлы и S3 (Supabase) ─────────────────────────────────────────────
# ── Обновленная настройка хранилищ для Django 5.2 ───────────────────────────
USE_S3 = os.environ.get('USE_S3', 'False') == 'True'

STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
    "default": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage" if USE_S3 else "django.core.files.storage.FileSystemStorage",
    },
}

# Если включен S3, прокидываем настройки S3 здесь
if USE_S3:
    AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME', 'cvai-media')
    AWS_S3_ENDPOINT_URL = os.environ.get('AWS_S3_ENDPOINT_URL')
    AWS_S3_REGION_NAME = os.environ.get('AWS_S3_REGION_NAME', 'eu-central-1')
    AWS_DEFAULT_ACL = 'public-read'
    AWS_QUERYSTRING_AUTH = False
    AWS_S3_FILE_OVERWRITE = False
    
    # 1. Supabase requires Signature Version 4
    AWS_S3_SIGNATURE_VERSION = 's3v4'
    
    if not AWS_S3_ENDPOINT_URL:
        raise ValueError("You turned on USE_S3=True in .env, but forgot to add AWS_S3_ENDPOINT_URL!")
        
    # Формируем URL
    supabase_project_url = AWS_S3_ENDPOINT_URL.split('/storage')[0].split('//')[1]
    custom_domain = f"{supabase_project_url}/storage/v1/object/public/{AWS_STORAGE_BUCKET_NAME}"
    
    # 2. Tell django-storages to use this custom domain for generating file URLs
    AWS_S3_CUSTOM_DOMAIN = custom_domain
    MEDIA_URL = f"https://{custom_domain}/"

else:
    MEDIA_URL = '/media/'
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
