# Generated by Django 6.0.6 on 2026-06-16 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0003_jobapplication_airesult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airesult',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_results', to='generator.jobapplication'),
        ),
    ]
