# Generated by Django 6.0.7 on 2026-08-14 10:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0004_fix_airesult_nullable_cascade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='airesult',
            index=models.Index(fields=['user', '-created_at'], name='ai_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='airesult',
            index=models.Index(fields=['user', 'result_type'], name='ai_user_type_idx'),
        ),
        migrations.AddIndex(
            model_name='generation',
            index=models.Index(fields=['user', '-created_at'], name='gen_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['user', '-updated_at'], name='job_user_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['user', 'status'], name='job_user_status_idx'),
        ),
    ]
