# Generated by Django 6.0.7 on 2026-09-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0005_airesult_ai_user_created_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIUsageDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('model', models.CharField(max_length=100)),
                ('calls', models.PositiveIntegerField(default=0)),
                ('input_tokens', models.BigIntegerField(default=0)),
                ('output_tokens', models.BigIntegerField(default=0)),
            ],
            options={
                'ordering': ['-date', 'model'],
                'constraints': [models.UniqueConstraint(fields=('date', 'model'), name='ai_usage_day_model_uniq')],
            },
        ),
    ]
